### ISSUE TITLE
The Graph API needs an HTTPMethod parameter

### ISSUE THREAD

**Issue by jwt-sgg** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#10]
The Graph API does not provide an HTTPMethod as input, which is needed when deleting graph objects.  I will implement this feature if it is not already in development.

**Comment by noahcooper** [comment]
@jwt-sgg if you want to submit a PR for this, that'd be great. :)

**Comment by noahcooper** [comment]
This will also address https://github.com/jeduan/cordova-plugin-facebook4/issues/581.
