### ISSUE TITLE
Login error there is an error in logging you into this application. please try again later

### ISSUE THREAD

**Issue by krishna711** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#108]
Hi, I am facing login issue with release version of the ionic app. Please help in debugging if anyone else faced same issue and resolved.

This issue occur when native app is installed. If native app is uninstalled then login flow works fine using chrome browser.

![image](https://user-images.githubusercontent.com/2379768/144222423-27f6af4a-bc76-40a4-8753-761fea2d945c.png)

This is only happening with release build. Debug build works fine with native app and without native app using chrome browser.

Added debug and release key hashes in facebook developer settings. Generated key hash from windows using specific openssl version given in troubleshooting page. 
Facebook developer setting deep link is ON.

Thanks for the help in advance.

**Comment by lucasgalli** [comment]
I am facing this issue too

**Comment by krishna711** [comment]
I fixed it by importing login behavior and force plugin to use web_view only instead of using native app. This is not ideal fix and should be consider temporary fix. I hope over time we will have correct solution. 

import com.facebook.login.LoginBehavior; // add on top
add below lines.

![image](https://user-images.githubusercontent.com/2379768/144715212-0b4b11f4-efae-4096-a9b8-eb66e77a76f0.png)

**Comment by krishna711** [comment]
This issue has resolved. Closing this issue.

Note for anyone facing this issue even after adding release key hashes in facebook developer settings.

I was doing big mistake and lost many hours testing this without luck. I was testing release signed build directly in emulator and device. The result was above error. Then I decide to upload in play store and check the build as internal beta test in closed circle  without open to public user. The logins were working just fine. 

If you are facing same issue test build in playstore and check if issue resolved.
