### ISSUE TITLE
Email is not retuned from facebookConnectPlugin.api

### ISSUE THREAD

**Issue by jasonandress** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#12]
**Bug or feature request**

[X ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Old plugin returns email, new plugin does not.

**Expected Behavior**

Return email as the old one did

**Sample repo**

facebookConnectPlugin.api("me/?fields=id,name,email&access_token=" + success.authResponse.accessToken, ["public_profile", "email"],

Same exact code for old and new plugin. cordova-plugin-facebook4 (old returns email) and cordova-plugin-facebook-connect (latest does not return email)

**Plugin version, OS, devices, etc**

Ionic:

   Ionic CLI         : 6.12.1 (/Users/jasonandress/.nvm/versions/node/v12.6.0/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 2.0.20

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 24 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/jasonandress/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.6.0 (/Users/jasonandress/.nvm/versions/node/v12.6.0/bin/node)
   npm               : 6.14.11
   OS                : macOS Big Sur
   Xcode             : Xcode 12.3 Build version 12C33

**Comment by jasonandress** [comment]
Here's the debug from the graph API using my auth token.

{
   "data": [
      {
         "permission": "email",
         "status": "granted"
      },
      {
         "permission": "public_profile",
         "status": "granted"
      }
   ],
   "__debug__": {
      
   }
}

**Comment by noahcooper** [comment]
It looks like this is caused by some change introduced in v8.1.0 of the Facebook SDK. This works in v8.0.0, but not v8.1.0. Will need to research a bit more to see why that is.

**Comment by noahcooper** [comment]
This was caused by a change made in the iOS SDK to address https://github.com/facebook/facebook-ios-sdk/issues/1403. As of v8.1.0 of the SDK, the "fields" parameter was being set to an empty string by default. I've fixed the plugin to ensure this doesn't happen.
