### ISSUE TITLE
not opening the fb app, opening in embedded. browser only

### ISSUE THREAD

**Issue by msd117** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#30]
I am trying to use this plugin in ios 13.6.1 iphone se 
when i make the login call it always open in the embedded browser and not in the facebook app.

i have checked stackoverflow and other platform and made the changes suggested such as. enable single sign on and other

please if anyone else is facing the same problem then please drop a comment 

also the android build is failing because of the Dex error ..

**Comment by noahcooper** [comment]
Facebook moved away from opening the native app for login in its SDK several years ago. This is not something this plugin can control.

Can you provide more information about the dex error you're referring to? And can you confirm you're using this plugin, and have removed `cordova-plugin-facebook4`?

**Comment by noahcooper** [comment]
I'm closing this, as the originally reported issue is a feature of the Facebook SDK.
