### ISSUE TITLE
getDeferredApplink does not correctly return deep link on iOS

### ISSUE THREAD

**Issue by noahcooper** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#42]
https://github.com/jeduan/cordova-plugin-facebook4/issues/217
https://github.com/jeduan/cordova-plugin-facebook4/issues/851
https://github.com/jeduan/cordova-plugin-facebook4/issues/868
https://github.com/facebook/facebook-ios-sdk/issues/1457

**Comment by SnowBases** [comment]
Any update on this?

**Comment by noahcooper** [comment]
@SnowBases this is targeted for the next major release, which is blocked until Facebook releases v10 of its SDK.

**Comment by RedSyInc** [comment]
Works on ios 14.5. Before use getDeferredApplink needs to get ads tracking permission and setAdvertiserTrackingEnabled to true. Tested with https://developers.facebook.com/tools/app-ads-helper/

**Comment by noahcooper** [comment]
@RedSyInc when you say this works, are you saying you get back a URL in the success callback?

I tested by calling `setAdvertiserTrackingEnabled` first.

```
facebookConnectPlugin.setAdvertiserTrackingEnabled(true);
```

I then used the App Ads Helper to trigger a test deep link. Once the app opened, I called:

```
facebookConnectPlugin.getDeferredApplink(function(url) {
  console.log('url = ' + url);
});
```

No URL is returned.

**Comment by noahcooper** [comment]
I can confirm this works as expected on Android, so the issue is only on iOS.

**Comment by noahcooper** [comment]
The missing link on iOS is that you must use a plugin such as [cordova-plugin-idfa](https://www.npmjs.com/package/cordova-plugin-idfa) to first request tracking permission. Only then can you use `getDeferredApplink`.

Example:

```
cordova.plugins.idfa.requestPermission().then(function() {
  facebookConnectPlugin.setAdvertiserTrackingEnabled(true);
  facebookConnectPlugin.getDeferredApplink(function(url) {
    console.log('url = ' + url);
  });
});
```

I'll update the docs to note this.
