### ISSUE TITLE
14.5 > IDFA requires to ask for user Permission

### ISSUE THREAD

**Issue by berseck** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#44]
[ ] I'm reporting a reproducible issue with the code
[x] I'm reporting a feature request

**Describe the Bug of feature request**

Need to add the ask permission for use track data

**Expected Behavior**

Use the ATTrackingManager to request user permission to use his data

**Plugin version, OS, devices, etc**

IOS 14.5 >

**Additional Context**

For the 14.5 > the IDFA requests that you request user permission to use his data or track him
Utilizing the:

```
//ask for user permission
- (bool) requestUserPermissionForIDFA() { 
  if (@available(iOS 14, *)) {
    [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
      if(status == ATTrackingManagerAuthorizationStatusAuthorized) {
        return YES;
      } 
        return NO;
      }
  }
}
```

**Comment by noahcooper** [comment]
As this is not strictly related to the Facebook SDK, and is something that developers need to do to use a number of different services that rely on IDFA not just Facebook, I don't think it makes sense to expose any methods related to ATT in this plugin. Instead, I'd recommend using a plugin like [cordova-plugin-idfa](https://www.npmjs.com/package/cordova-plugin-idfa).

**Comment by berseck** [comment]
> As this is not strictly related to the Facebook SDK, and is something that developers need to do to use a number of different services that rely on IDFA not just Facebook, I don't think it makes sense to expose any methods related to ATT in this plugin. Instead, I'd recommend using a plugin like [cordova-plugin-idfa](https://www.npmjs.com/package/cordova-plugin-idfa).

Actually it states that if you want to use the methods: 
```
[FBSDKSettings setAdvertiserTrackingEnabled:YES];
[FBSDKSettings setAdvertiserIDCollectionEnabled:YES];
```

You must ask permissions first.
It's in their manual.

> Get Device Consent
Starting with iOS 14.5, you will need to set AdvertiserTrackingEnabled and log each time you give a device permission to share data with Facebook. If a device provides consent, call the setAdvertiserTrackingEnabled method of the FBSDKSettings class and set it to YES for Objective-C or true for Swift. If a device does not allow tracking, set setAdvertiserTrackingEnabled to NO for Objective-C or false for Swift. The method will return a boolean value to indicate whether the method is set successfully or not.

https://developers.facebook.com/docs/app-events/getting-started-app-events-ios

**Comment by noahcooper** [comment]
@berseck understood, and this plugin exposes those methods specific to the Facebook SDK. My point is that 
App Tracking Transparency is not specific to Facebook, so methods related to it really don't belong in this plugin. Instead, you can use `cordova-plugin-idfa` and its `requestPermission` method.

**Comment by berseck** [comment]
Points taken thank you for your explanation.
