### ISSUE TITLE
Podfile not replacing $FACEBOOK_IOS_SDK_VERSION / installing failed

### ISSUE THREAD

**Issue by reesz** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#52]
**Describe the Bug of feature request**

When trying to install this plugin via: 
`cordova plugin add cordova-plugin-facebook-connect --save --variable APP_ID="APP_ID" --variable APP_NAME="APP NAME"`

the command always fails with the following error output:
```
Installing "cordova-plugin-facebook-connect" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-facebook-connect" for browser
6.0.0
Installing "cordova-plugin-facebook-connect" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-facebook-connect': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/...path-to-project.../node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
pod: Command failed with exit code 1

```

Since it seems to only fail on "installing for ios" I tried installing the pods manually and saw, that the Podfile looked like this:

```
target 'Project' do
	project 'Project.xcodeproj'
	pod 'OneSignal', '2.14.2'
	pod 'FirebaseMessaging', '~> 2.0.0'
	pod 'FBSDKCoreKit', '$FACEBOOK_IOS_SDK_VERSION'
	pod 'FBSDKLoginKit', '$FACEBOOK_IOS_SDK_VERSION'
	pod 'FBSDKShareKit', '$FACEBOOK_IOS_SDK_VERSION'
end
```

and when running `pod install` manually it obviously can't resolve the `$FACEBOOK_IOS_SDK_VERSION` variable.
I tried replacing them manually with `9.0.1.` as provided in `ios.json`, which works for the `pod install` command, but leaves other build errors, since the plugin install probably hasn't finished correctly.

**Expected Behavior**

Expected the install command to run without errors.

**Plugin version, OS, devices, etc**

Newest plugin version 2.1.0.
```
Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/reesz/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v11.15.0 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 12.3 Build version 12C33

```

**Additional Context**

Already tried following the trouble shooting for iOS here: https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/blob/master/docs/ios/README.md
and updated pods, pods repo and cocoa pods.

Is there anything I am missing here? I'll leave anyone a coffee who can point me towards the solution.

Thanks for your time! 🙏

**Comment by noahcooper** [comment]
It looks like the build fails only in cordova-ios 5. I'll look at fixing this in the next minor release, but I'd recommend upgrading to cordova-ios 6, as the next major release will require it (https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/40).

**Comment by noahcooper** [comment]
This was indeed a bug fixed in cordova-ios 6:

https://github.com/apache/cordova-ios/issues/721

**Comment by vesper8** [comment]
I'm already using `"cordova-ios": "^6.2.0",` but am having this error anyway... bit stumped at the moment
