### ISSUE TITLE
Update facebook sdk pods got error on build

### ISSUE THREAD

**Issue by ZumelzuR** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#55]
[x] I'm reporting a reproducible issue with the code
[x] I'm reporting a feature request

**Describe the Bug of feature request**

Hello, I want to update the facebook sdk, so I edit manually the pods file at platform/ios like:

	pod 'FBSDKCoreKit', '8.0.0'
	pod 'FBSDKLoginKit', '8.0.0'
	pod 'FBSDKShareKit', '8.0.0'

The problem is that then when I build for "ios" I got an error on the FacebookConnectPlugin.m file at /Users/<myuser>/../platforms/ios/Seaver/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m

I attached a picture with the missing stuff and alerts on the file.

**Expected Behavior**

Should build without problems, but I suspect that we need to update the code of the ios part of the plugin in order to adjust to the last facebook sdk, without this new sdk I think all facebook features will not work on ios 14.

I'm not super experienced in objective-c but if you give me some advice I can make the changes and do the pr 

**Plugin version, OS, devices, etc**

 I used last version of the plugin and:
 ionic v3
 cordova 9.0.0
 cordova-ios 6.0.0

<img width="753" alt="Captura de pantalla 2021-03-16 a las 16 38 01" src="https://user-images.githubusercontent.com/2078029/111337512-727d2880-8676-11eb-9b54-718ce69970b4.png">

**Comment by noahcooper** [comment]
@ZumelzuR I think you might still be using `cordova-plugin-facebook4` and not this plugin. The line you highlighted was removed from this plugin. Also, this plugin currently uses v9 of the Facebook SDK. Finally you should not need to ever edit `Podfile` to use a different version of the SDK, as you can pass `FACEBOOK_IOS_SDK_VERSION` when installing the plugin.

**Comment by ZumelzuR** [comment]
thanks for the early response, yes you right, actually I was thinking that I posted this on the facebook-4 plugin xD. 

Yes I just realized that cordova-plugin-facebook4 is deprecated, I changed to this plugin and work cool, thank you
