### ISSUE TITLE
AndroidX / Program type already present: android.support.customtabs.ICustomTabsCallback$Stub

### ISSUE THREAD

**Issue by reesz** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#59]
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

After installing the plugin, android build fails with the following error:
```
D8: Program type already present: android.support.customtabs.ICustomTabsCallback$Stub

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.customtabs.ICustomTabsCallback$Stub
```

**Expected Behavior**

Expected the build to finish.

**Plugin version, OS, devices, etc**
Plugin-Version: 2.2.0
**ionic info:**
```
Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/XXX/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v11.15.0 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 12.3 Build version 12C33

```

**Additional Context**

Checking the link in the error message, it says this should be resolved by removing one of the duplicated dependencies.
Using `./gradlew app:dependencies` to list the deps-tree gives this output: https://pastebin.com/pk6W0VRp

Showing that `com.android.support:customtabs` is listed twice. This doesn't seem to be the problem though, because after removing `cordova-plugin-facebook-connect` the output is this: https://pastebin.com/5yauyCmg
Still listing `com.android.support:customtabs` twice, but not producing an error on build.

Only stripping out the diff between these two dep-trees are these:
https://pastebin.com/qWHWVNGG

Leading me to the idea that this might be caused by the AndroidX-dependencies? 
Since we're an older version of ionic not yet migrated to AndroidX because of budget & some older plugins being used.

**Important note**

Appreciate the support for these possibly legacy issues and would still be willing to compensate for the time.

Thanks for the time.

**Comment by reesz** [comment]
Even though remembering a failed try to migrate to AndroidX in the past, I gave it another shot and found this quick solution:
https://forum.ionicframework.com/t/migrating-ionic-app-to-androidx/160844

```bash
# add plugin to enable AndroidX in the project
cordova plugin add cordova-plugin-androidx

# add plugin to patch existing plugin source that uses the Android Support Library to use AndroidX
cordova plugin add cordova-plugin-androidx-adapter
```

adding these and afterwards installing the `cordova-plugin-facebook-connect` – I was able to build the release again. Will see if this has any other sideeffects.

**Comment by noahcooper** [comment]
@reesz yes, like you said, if you are using an older version of Cordova, you need `cordova-plugin-androidx` to use AndroidX (AndroidX is supported in the most recent version of `cordova-android` without any plugin). If you have plugins that haven't been updated to migrate to Androidx, `cordova-plugin-androidx-adapter` is required as well.

Glad you figured it out!
