### ISSUE TITLE
Update Facebook SDK for iOS from 9.1.0 to 9.2.0.

### ISSUE THREAD

**Issue by bobisum** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#63]
Can you please update the iOS SDK to the latest version?

**Comment by noahcooper** [comment]
The default SDK version for Android and iOS will be updated in the next minor release. In the meantime, you can use the `FACEBOOK_IOS_SDK_VERSION` variable to set a version on your own, e.g.

```
cordova plugin add cordova-plugin-facebook-connect --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable FACEBOOK_IOS_SDK_VERSION="9.2.0"
```
