### ISSUE TITLE
- (BOOL)swizzled_application methods calling themselves recursively can crash the app

### ISSUE THREAD

**Issue by uareurapid** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#65]
**Bug or feature request**

[ x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Is there any reasonable explanation why both methods listed bellow are calling themselves recursively? Am I missing something?  I mean, just by looking at the code it  feels wrong.
I had the wrong behaviour with the original plugin and it still persists on this fork.
Whenever one of these methods are called they simply crash the app because they call themselves over and over again

```
- (BOOL)swizzled_application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
....
return [self swizzled_application:application openURL:url options:options];
```

```
- (BOOL)swizzled_application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
....
return [self swizzled_application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
```

**Expected Behavior**

we should add a `return YES` at the end of statement and remove the recursive call

**Sample repo**

A sample repo is needed for this issue to be fixed, please provide one in order to reproduce the problem.

You could for example try to use the [cordova-plugin-facebook-connect-lab](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect-lab) to reproduce your issue.

**Plugin version, OS, devices, etc**

Latest plugin version, IOS

**Additional Context**

It happens when the app is opened using an url scheme (deeplink or similar)

**Important note**

**Comment by noahcooper** [comment]
@uareurapid Could you possibly provide some additional reproduction steps to observe a crash? You mentioned deep links, but the apps I develop use deep links and I have not observed crashes.

If you can help with some more details, I can look at updating this in the next major release. This code is already being significantly changed as part of dropping support for iOS 8, which is what half of the code in question is for.

**Comment by uareurapid** [comment]
basically I was just following a link to open the IOS app via the url scheme, something 
like **app://my_native_app_scheme** The context of the link is specific to the app, but could be by either pasting the url directly on the browser or just calling the window.open() method from javascript.
In any case, I think is easy to understand that those lines of code are not OK, since they are recursive to themselves. If that code is ever reached the outcome can only result in draining the stack and causing the app to crash
