### ISSUE TITLE
Graph API upgrade

### ISSUE THREAD

**Issue by najilouis** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#66]
I got the following alert:

> Your App, is currently accessing Graph API v3.2 which will reach the end of its 2-year lifetime on 04 May, 2021. We estimate 1 endpoint that Inztasac calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v3.3 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

How can I change the used Graph API version ?

I saw in the readme file that this plugin will always be released for iOS and for Android with a synchronized usage of the Facebook SDKs and the Graph API is related to the released SDK.

**Comment by noahcooper** [comment]
Are you sure you're using this plugin, and not `cordova-plugin-facebook4`? v3.2 pre-dates this plugin. The most recent version of this plugin uses v9 of the Graph API, the next major release will use v10 (once Facebook updates its SDKs to use it).

**Comment by najilouis** [comment]
I was using cordova-plugin-facebook4 then I replaced by this new plugin.
I did this replacement 3 months ago so maybe some users still using the old version.

**Comment by noahcooper** [comment]
Good point -- yes, users who have not updated your app could still be using the version of your code that uses `cordova-plugin-facebook4` and thus the older version of the Graph API. The good news is that Facebook automatically upgrades API calls if you're using an older version.
