### ISSUE TITLE
Facebook Analytics will no longer be available 

### ISSUE THREAD

**Issue by gelinger777** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#72]
Facebook Analytics will no longer be available after June 30, 2021. Will this impact your module? 
I wanted to implement it just to track App Installs for Facebook Ads. Can I still do it?

**Comment by noahcooper** [comment]
This doesn't affect this plugin. You can still use other Facebook tools like Events Manager for tracking events.
