### ISSUE TITLE
Reauthenticate user using a different account

### ISSUE THREAD

**Issue by antoine92190** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#74]
Could we implement the reauthenticate feature?
When we logging with a user, there is currently now way to reauthenticate using another account.
The idea would be to implement that: https://developers.facebook.com/docs/facebook-login/reauthentication/

**Comment by noahcooper** [comment]
See this note on the page you linked to:

```
The Android and iOS SDKs don't currently support re-authentication.
```
