### ISSUE TITLE
Error: Can't load URL: The domain of this url isn't ... 

### ISSUE THREAD

**Issue by JonasWestAlro** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#75]
I got this error on IOS. 
Feel like I've tried everything, so any help would be greatly appreciated.. 

The error is: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

![IMG_946A7D056935-1](https://user-images.githubusercontent.com/6217506/126798151-2a7aeadf-0023-4e7c-b1b2-2d1fa0e016b4.jpeg)

**Comment by noahcooper** [comment]
If you edit your app on https://developers.facebook.com/apps and navigate to Facebook Login -> Settings, could you tell me the values of each of the Yes/No switches under "Client OAuth Settings"? I suspect one of those is to blame.

**Comment by kosbar** [comment]
get the same error here and in logs i saw this:
_FBSDKLog: Starting with v13 of the SDK, a client token must be embedded in your client code before making Graph API calls. Visit https://developers.facebook.com/docs/ios/getting-started#step-3---configure-your-project to learn how to implement this change._
so when I add in plist this options:
```xml
<key>FacebookClientToken</key>
<string>CLIENT-TOKEN</string>
```
with Client Token from Advanced section of main settings in FB console it helps.

**Comment by noahcooper** [comment]
Thanks @kosbar. The next major release of this plugin will require a client token, see https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/70.

**Comment by kosbar** [comment]
I really would like to know what the simplest configuration of FB app with simplest plist.
I have broke my configuration again!!!

**Comment by noahcooper** [comment]
@kosbar you shouldn't need to do anything to your plist file to get your app to work, and more than likely the issue described here has nothing to do with this plugin. This is likely some combination of settings under Facebook Login -> Settings, I'm just not sure which yet.

**Comment by kosbar** [comment]
I found out the solving my problem: I remove all mention of FACEBOOK_URL_SCHEME_SUFFIX from .plist!
We use 11 SDK and 11 Graph API in FB-console.
Probably you should remove it from .plist at all if app didn't mention it in package.json config.

**Comment by kosbar** [comment]
> @kosbar you shouldn't need to do anything to your plist file to get your app to work, and more than likely the issue described here has nothing to do with this plugin. This is likely some combination of settings under Facebook Login -> Settings, I'm just not sure which yet.
> 
> Can you confirm which method you're calling when you see this error message?

I found out the solving my problem: I remove all mention of FACEBOOK_URL_SCHEME_SUFFIX from .plist!
We use 11 SDK and 11 Graph API in FB-console.
Probably you should remove it from .plist at all if app didn't mention it in package.json config.

**Comment by noahcooper** [comment]
@kosbar "FACEBOOK_URL_SCHEME_SUFFIX" doesn't appear anywhere in the plist. If you're seeing "FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER" in the plist, that means for some reason the after_prepare hook didn't executed. It should be executed any time you run any of the following:

```
cordova prepare
cordova platform add
cordova build
cordova run
```

**Comment by mariogarranz** [comment]
I am having the same issue and I noticed the OAuth request was sending these values:

```
local_client_id: FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER
redirect_uri: fb123456789FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER://authorize/
```

Where 123456789 is my app ID. So apparently I'm having the same issue, that FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER is not being properly replaced, and this happens even if I run cordova prepare ios.

If I check the Info.plist I find there are 3 placeholder keys there using default values:

FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER
FACEBOOK_AUTO_LOG_APP_EVENTS_PLACEHOLDER
FACEBOOK_ADVERTISER_ID_COLLECTION_PLACEHOLDER

This is mentioned in #97 and seems to be linked to this bug.

**Comment by mariogarranz** [comment]
For anyone having this issue, as @noahcooper mentioned, these values should be automatically filled when running the prepare command, but apparently any minor issue with config.xml may prevent them from being filled.

In my case the problem was related to an iOS icon listed in config.xml missing in the linked directory. This resulted in a valid iOS build, but with these values not properly filled.

**Comment by sfeast** [comment]
> @kosbar "FACEBOOK_URL_SCHEME_SUFFIX" doesn't appear anywhere in the plist. If you're seeing "FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER" in the plist, that means for some reason the after_prepare hook didn't get executed. It should be executed any time you run any of the following:
> 
> ```
> cordova prepare
> cordova platform add
> cordova build
> cordova run
> ```

@noahcooper I'm seeing these placeholder values in my plist if I run just `cordova prepare` but if I run `cordova prepare ios` then they are removed 🤷‍♂️ 

I can reproduce this with even a new/barebones cordova project & only adding this plugin.

Using:
cordova 10.0.0
cordova ios platform 6.2.0
Xcode 13.0

**Comment by NorthNick** [comment]
> > @kosbar "FACEBOOK_URL_SCHEME_SUFFIX" doesn't appear anywhere in the plist. If you're seeing "FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER" in the plist, that means for some reason the after_prepare hook didn't get executed. It should be executed any time you run any of the following:
> > ```
> > cordova prepare
> > cordova platform add
> > cordova build
> > cordova run
> > ```
> 
> @noahcooper I'm seeing these placeholder values in my plist if I run just `cordova prepare` but if I run `cordova prepare ios` then they are removed 🤷‍♂️
> 
> I can reproduce this with even a new/barebones cordova project & only adding this plugin.
> 
> Using: cordova 10.0.0 cordova ios platform 6.2.0 Xcode 13.0

I also see the same behaviour: a barebones Cordova project with the plugin added creates a plist file with the three placeholder entries. Leaving them in makes Facebook login fail, while removing them makes it work.

Creating a barebones Ionic project, and adding just this plugin and the Ionic Facebook plugin creates a plist file without the placeholder entries, and logging in works fine immediately. (Comparing the plist files was how I stumbled across the solution to this problem, which has been plaguing me for a week now.)

**Comment by sebafra** [comment]
In info.plist i´ve replaced the APP_ID like following:

`<string>fb$APP_IDFACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER</string>`
with
`<string>fb123456789FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER</string>`
where 123456789 is the APP_ID

And it works!!!!
