### ISSUE TITLE
FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER null

### ISSUE THREAD

**Issue by expcapitaldev** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#77]
do you know "FACEBOOK_URL_SCHEME_SUFFIX_PLACEHOLDER" null set into plist file ?

**Comment by expcapitaldev** [comment]
see https://github.com/expcapitaldev/cordova-plugin-facebook-connect/commit/5331fb175a786c98d6aff6fdbd05fc438be45f26#diff-e04c603577d2f62815f49034f082f630a2c93ee04dac14aa1ba0b20f5e88d004R43

**Comment by noahcooper** [comment]
Thanks @expcapitaldev! This is fixed in the next major release.
