### ISSUE TITLE
Later initialize with AppId

### ISSUE THREAD

**Issue by EinfachHans** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#78]
**Bug or feature request**

- [ ] I'm reporting a reproducible issue with the code
- [X] I'm reporting a feature request

**Describe the feature request**

Currently i have to enter the AppId as Variable. I want to be able to initialize the Plugin with a specific AppId from Code. Is this possible with the Facebook SDK's?

So maybe add a variable "init_on_start" which is settable to "false" and the from my AppCode call `init(appId)`?

**Comment by noahcooper** [comment]
In the next major release, you'll be able to use `setApplicationId` and `setApplicationName`. You'll still be required to init with one App ID (since it's required in the Android manifest and *-Info.plist files), but then you can change that in code as you see fit.

**Comment by EinfachHans** [comment]
@noahcooper amazing! Any Progress you can share on the next major version? 😊

**Comment by noahcooper** [comment]
@EinfachHans it'll be released tomorrow.
