### ISSUE TITLE
When targeting Android SDK 30 ShareDialog opens webview instead

### ISSUE THREAD

**Issue by ValterdeJesus** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#81]
Hi. Doing some tests here, noticed that when setting android-targetSdkVersion to 30, the share dialog won't open. Instead it will open a webview with facebook mobile inside where it requests for login and password. I think this is related to the android file system changes on Android 11. thanks.

**Comment by noahcooper** [comment]
Thanks @ValterdeJesus. This does appear to be an issue with Android 11 package visibility.
