### ISSUE TITLE
5th October 2021: no more support Android embedded browsers (WebViews) for logging in users

### ISSUE THREAD

**Issue by giorgiobeggiorasoprasteria** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#85]
Good morning,

is the plugin compliant with this?

https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews

I'm using 2.2.0 and I wasn't aware about any "login behavior = webview only/custom tab" option.

Thanks.

**Comment by dland512** [comment]
What's the minimum version of this plugin that will work after Oct 5, 2021?
