### ISSUE TITLE
How to check SDK version

### ISSUE THREAD

**Issue by dland512** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#94]
Like many people, I recently got a message from facebook stating that they will [no longer supporting android webviews](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) after October 5, 2021.

Based on a few other posts [here](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/82) and [here](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/85) it looks as though this plugin will still work without the facebook app installed as long as it uses SDK version 8.2.0 or greater.

My question is how can I check which version of the Facebook SDK comes with the version of this plugin I have installed? 
I have version `1.1.0` of this plugin and inside `cordova-plugin-facebook-connect/plugin.xml` I see this

```
<preference name="FACEBOOK_ANDROID_SDK_VERSION" default="8.1.0"/>
```

Is that the correct value?

**Comment by noahcooper** [comment]
@dland512 you can check `plugin.xml` for the default SDK version, but of course, you have the ability to override the version when adding the plugin to your project using the `FACEBOOK_ANDROID_SDK_VERSION` preference. For example:

```
cordova plugin add cordova-plugin-facebook-connect --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable FACEBOOK_ANDROID_SDK_VERSION="8.2.0"
```

You can check the [CHANGELOG](../blob/master/CHANGELOG.md) for details on each release, including when the default SDK version was updated. Major versions of this plugin align with major versions of the Facebook SDK and Graph API, e.g. v1 is v8, v2 is v9, v3 is v11 (Facebook never released v10), v4 will be v12.

**Comment by dland512** [comment]
Great info, thank you!
