### ISSUE TITLE
 iOS facebook login opens safari instead of native app

### ISSUE THREAD

**Issue by jurahalas** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#96]

**Comment by marioshtika** [comment]
I have the same problem.

@jurahalas did you find a solution for this?

**Comment by marioshtika** [comment]
It looks like this is the default behavior since iOS 9 (October 2019)
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

I have been using `jeduan/cordova-plugin-facebook4` until now where I am guessing it was using the previous SKD where opening the nave app was possible.

**Comment by noahcooper** [comment]
@marioshtika is correct. This is expected behavior for iOS.
