### ISSUE TITLE
Login in iOS loops between facebook pop up and facebook app

### ISSUE THREAD

**Issue by deficts** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#99]
I'm having trouble with login to my app, when trying the facebook login it opens up the popup and then it redirects you to the normal facebook app in the phone, when tapping "continue" in the facebook app it goes back to the popup and it loops between this two states without performing the login.

**State 1 (Own app)**
<img src="https://user-images.githubusercontent.com/42699458/135699087-6be66fad-1773-4dd0-9dd7-d75110649013.PNG" width="200">

**State 2 (Facebook app)**
<img src="https://user-images.githubusercontent.com/42699458/135699092-7014997a-7c77-4b67-af7d-ffda1fd3dc45.PNG" width="200">

I'm using ionic with capacitor version 3.1.2 and the version 3.2.0 of this plugin

Thanks in advance for any help!

**Comment by deficts** [comment]
Found out what the issue was:

We had this key value in our `info.plist` 
```
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbauth2</string>
	</array>
[...]
```
after removing `<string>fbauth2</string>`, the webview opens and you are able to enter your facebook credentials.

**Comment by coldiary** [comment]
Maybe I'd suggest reopening this issue. I don't think removing fbauth2 scheme is expected.
On our side it prevents the native app to open for login.
